<?xml version="1.0" encoding="UTF-8"?>

<project
        xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
        http://maven.apache.org/xsd/maven-4.0.0.xsd"
>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.dwarfeng</groupId>
    <artifactId>subgrade</artifactId>
    <version>2.0.0.a-SNAPSHOT</version>

    <packaging>pom</packaging>

    <name>subgrade</name>
    <url>https://github.com/DwArFeng/subgrade</url>

    <properties>
        <!-- 进行工程编码声明 -->
        <!-- 进行 JDK 版本声明 -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.release>25</maven.compiler.release>
        <!-- 进行资源的统一声明 -->
        <!-- 进行版本声明 -->
        <!-- 集中定义依赖版本号 -->
        <jetbrains-annotations.version>26.1.0</jetbrains-annotations.version>
        <junit.version>6.1.2</junit.version>
        <log4j2.version>2.26.1</log4j2.version>
        <slf4j.version>2.0.18</slf4j.version>
        <commons-logging.version>1.3.5</commons-logging.version>
        <jakarta-servlet.version>6.1.0</jakarta-servlet.version>
        <jakarta-persistence.version>3.2.0</jakarta-persistence.version>
        <jakarta-transaction.version>2.0.1</jakarta-transaction.version>
        <jakarta-cdi.version>4.1.0</jakarta-cdi.version>
        <jakarta-interceptor.version>2.2.0</jakarta-interceptor.version>
        <jakarta-validation.version>3.1.1</jakarta-validation.version>
        <jakarta-xml-bind.version>4.0.4</jakarta-xml-bind.version>
        <commons-io.version>2.22.0</commons-io.version>
        <spring-framework.version>7.0.8</spring-framework.version>
        <spring-data.version>2026.0.0</spring-data.version>
        <micrometer.version>1.17.0</micrometer.version>
        <netty.version>4.2.9.Final</netty.version>
        <zookeeper.version>3.9.5</zookeeper.version>
        <guava.version>33.6.0-jre</guava.version>
        <error-prone-annotations.version>2.47.0</error-prone-annotations.version>
        <curator.version>5.9.0</curator.version>
        <dubbo.version>3.3.6</dubbo.version>
        <hibernate-orm.version>7.4.5.Final</hibernate-orm.version>
        <mybatis.version>3.5.19</mybatis.version>
        <mybatis-spring.version>4.1.0</mybatis-spring.version>
        <jaxb-runtime.version>4.0.7</jaxb-runtime.version>
        <hibernate-validator.version>9.1.2.Final</hibernate-validator.version>
        <expressly.version>6.0.0</expressly.version>
        <fastjson2.version>2.0.61</fastjson2.version>
        <aspectj.version>1.9.25.1</aspectj.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <kafka.version>4.3.1</kafka.version>
        <dutil.version>2.0.1.a</dutil.version>
        <!-- Maven 插件版本声明 -->
        <maven-clean-plugin.version>3.5.0</maven-clean-plugin.version>
        <maven-resources-plugin.version>3.4.0</maven-resources-plugin.version>
        <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
        <maven-surefire-plugin.version>3.5.4</maven-surefire-plugin.version>
        <maven-source-plugin.version>3.4.0</maven-source-plugin.version>
        <maven-deploy-plugin.version>3.1.4</maven-deploy-plugin.version>
        <maven-enforcer-plugin.version>3.6.2</maven-enforcer-plugin.version>
        <maven-dependency-plugin.version>3.9.0</maven-dependency-plugin.version>
        <!-- Surefire 参数定义 -->
        <project.surefire.skip>true</project.surefire.skip>
    </properties>

    <!-- 声明资源的坐标 -->
    <!-- 只定义依赖的版本，并不实际依赖 -->
    <dependencyManagement>
        <dependencies>
            <!-- JetBrains 静态注解 -->
            <dependency>
                <groupId>org.jetbrains</groupId>
                <artifactId>annotations</artifactId>
                <version>${jetbrains-annotations.version}</version>
            </dependency>
            <!-- 单元测试 -->
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- 日志处理 -->
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-bom</artifactId>
                <version>${log4j2.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-logging</groupId>
                <artifactId>commons-logging</artifactId>
                <version>${commons-logging.version}</version>
            </dependency>
            <!-- Jakarta Servlet -->
            <dependency>
                <groupId>jakarta.servlet</groupId>
                <artifactId>jakarta.servlet-api</artifactId>
                <version>${jakarta-servlet.version}</version>
            </dependency>
            <!-- Jakarta Persistence -->
            <dependency>
                <groupId>jakarta.persistence</groupId>
                <artifactId>jakarta.persistence-api</artifactId>
                <version>${jakarta-persistence.version}</version>
            </dependency>
            <!-- Jakarta Transaction -->
            <dependency>
                <groupId>jakarta.transaction</groupId>
                <artifactId>jakarta.transaction-api</artifactId>
                <version>${jakarta-transaction.version}</version>
            </dependency>
            <!-- Jakarta CDI -->
            <dependency>
                <groupId>jakarta.enterprise</groupId>
                <artifactId>jakarta.enterprise.cdi-api</artifactId>
                <version>${jakarta-cdi.version}</version>
            </dependency>
            <!-- Jakarta Interceptor -->
            <dependency>
                <groupId>jakarta.interceptor</groupId>
                <artifactId>jakarta.interceptor-api</artifactId>
                <version>${jakarta-interceptor.version}</version>
            </dependency>
            <!-- Jakarta Validation -->
            <dependency>
                <groupId>jakarta.validation</groupId>
                <artifactId>jakarta.validation-api</artifactId>
                <version>${jakarta-validation.version}</version>
            </dependency>
            <!-- Jakarta XML Bind -->
            <dependency>
                <groupId>jakarta.xml.bind</groupId>
                <artifactId>jakarta.xml.bind-api</artifactId>
                <version>${jakarta-xml-bind.version}</version>
            </dependency>
            <!-- Apache Commons 组件 -->
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons-io.version}</version>
            </dependency>
            <!-- Spring 框架 -->
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-framework-bom</artifactId>
                <version>${spring-framework.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-bom</artifactId>
                <version>${spring-data.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- Micrometer 可观测性组件 -->
            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-observation</artifactId>
                <version>${micrometer.version}</version>
            </dependency>
            <!-- Netty 网络框架 -->
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>${netty.version}</version>
            </dependency>
            <!-- Zookeeper 客户端 -->
            <dependency>
                <groupId>org.apache.zookeeper</groupId>
                <artifactId>zookeeper</artifactId>
                <version>${zookeeper.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>io.netty</groupId>
                        <artifactId>netty-handler</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>io.netty</groupId>
                        <artifactId>netty-transport-native-epoll</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>log4j</groupId>
                        <artifactId>log4j</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-log4j12</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>io.netty</groupId>
                        <artifactId>netty-tcnative-boringssl-static</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <!-- Guava 工具库 -->
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.errorprone</groupId>
                <artifactId>error_prone_annotations</artifactId>
                <version>${error-prone-annotations.version}</version>
            </dependency>
            <!-- Curator 组件 -->
            <dependency>
                <groupId>org.apache.curator</groupId>
                <artifactId>curator-framework</artifactId>
                <version>${curator.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.curator</groupId>
                <artifactId>curator-recipes</artifactId>
                <version>${curator.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.curator</groupId>
                <artifactId>curator-x-discovery</artifactId>
                <version>${curator.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.fasterxml.jackson.core</groupId>
                        <artifactId>jackson-databind</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <!-- Dubbo 微服务框架 -->
            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo</artifactId>
                <version>${dubbo.version}</version>
            </dependency>
            <!-- Hibernate 组件 -->
            <dependency>
                <groupId>org.hibernate.orm</groupId>
                <artifactId>hibernate-platform</artifactId>
                <version>${hibernate-orm.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- Mybatis 组件 -->
            <dependency>
                <groupId>org.mybatis</groupId>
                <artifactId>mybatis</artifactId>
                <version>${mybatis.version}</version>
            </dependency>
            <!-- Mybatis 集成 Spring 组件 -->
            <dependency>
                <groupId>org.mybatis</groupId>
                <artifactId>mybatis-spring</artifactId>
                <version>${mybatis-spring.version}</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jaxb</groupId>
                <artifactId>jaxb-runtime</artifactId>
                <version>${jaxb-runtime.version}</version>
            </dependency>
            <!-- Hibernate 验证器 -->
            <dependency>
                <groupId>org.hibernate.validator</groupId>
                <artifactId>hibernate-validator</artifactId>
                <version>${hibernate-validator.version}</version>
            </dependency>
            <!-- Jakarta EL 实现 -->
            <dependency>
                <groupId>org.glassfish.expressly</groupId>
                <artifactId>expressly</artifactId>
                <version>${expressly.version}</version>
            </dependency>
            <!-- FastJson Json 工具 -->
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson2.version}</version>
            </dependency>
            <!-- AspectJ 组件 -->
            <dependency>
                <groupId>org.aspectj</groupId>
                <artifactId>aspectjweaver</artifactId>
                <version>${aspectj.version}</version>
            </dependency>
            <!-- Mapstruct 框架 -->
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <!-- Kafka 客户端 -->
            <dependency>
                <groupId>org.apache.kafka</groupId>
                <artifactId>kafka-clients</artifactId>
                <version>${kafka.version}</version>
            </dependency>
            <!-- Dutil 工具库 -->
            <dependency>
                <groupId>com.dwarfeng</groupId>
                <artifactId>dutil-basic</artifactId>
                <version>${dutil.version}</version>
            </dependency>
            <!-- 程序自身组件 -->
            <dependency>
                <groupId>com.dwarfeng</groupId>
                <artifactId>subgrade-base</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.dwarfeng</groupId>
                <artifactId>subgrade-basic</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.dwarfeng</groupId>
                <artifactId>subgrade-data</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.dwarfeng</groupId>
                <artifactId>subgrade-expression</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.dwarfeng</groupId>
                <artifactId>subgrade-aop</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.dwarfeng</groupId>
                <artifactId>subgrade-web</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.dwarfeng</groupId>
                <artifactId>subgrade-lifecycle</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.dwarfeng</groupId>
                <artifactId>subgrade-cache</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.dwarfeng</groupId>
                <artifactId>subgrade-lock</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.dwarfeng</groupId>
                <artifactId>subgrade-kafka</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>${maven-clean-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>${maven-resources-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${maven-source-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>${maven-deploy-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${maven-enforcer-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>${maven-dependency-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <modules>
        <module>subgrade-base</module>
        <module>subgrade-basic</module>
        <module>subgrade-data</module>
        <module>subgrade-expression</module>
        <module>subgrade-aop</module>
        <module>subgrade-web</module>
        <module>subgrade-lifecycle</module>
        <module>subgrade-cache</module>
        <module>subgrade-lock</module>
        <module>subgrade-kafka</module>
    </modules>
</project>
