module com.dwarfeng.subgrade.data {

    requires com.dwarfeng.subgrade.base;
    requires com.dwarfeng.subgrade.basic;
    requires com.dwarfeng.dutil.basic;
    requires java.naming;
    requires java.sql;
    requires spring.beans;
    requires spring.jdbc;
    requires spring.tx;
    requires spring.data.redis;
    requires org.hibernate.orm.core;
    requires transitive jakarta.persistence;
    requires org.mybatis;
    requires org.mybatis.spring;
    requires com.alibaba.fastjson2;
    requires org.mapstruct;
    requires jakarta.xml.bind;
    requires org.glassfish.jaxb.runtime;
    requires org.slf4j;
    requires static org.jetbrains.annotations;
    requires org.jspecify;

    exports com.dwarfeng.subgrade.data.stack.cache;
    exports com.dwarfeng.subgrade.data.stack.dao;
    exports com.dwarfeng.subgrade.data.stack.exception;
    exports com.dwarfeng.subgrade.data.stack.handler;
    exports com.dwarfeng.subgrade.data.stack.service;
    exports com.dwarfeng.subgrade.data.sdk.bean.key.hibernate;
    exports com.dwarfeng.subgrade.data.sdk.database.ddl;
    exports com.dwarfeng.subgrade.data.sdk.database.definition;
    exports com.dwarfeng.subgrade.data.sdk.configuration;
    exports com.dwarfeng.subgrade.data.sdk.exception;
    exports com.dwarfeng.subgrade.data.sdk.hibernate.converter;
    exports com.dwarfeng.subgrade.data.sdk.hibernate.criteria;
    exports com.dwarfeng.subgrade.data.sdk.hibernate.hql;
    exports com.dwarfeng.subgrade.data.sdk.hibernate.hql.clause;
    exports com.dwarfeng.subgrade.data.sdk.hibernate.modification;
    exports com.dwarfeng.subgrade.data.sdk.hibernate.nativelookup;
    exports com.dwarfeng.subgrade.data.sdk.hibernate.operation;
    exports com.dwarfeng.subgrade.data.sdk.jdbc.handle;
    exports com.dwarfeng.subgrade.data.sdk.jdbc.processor;
    exports com.dwarfeng.subgrade.data.sdk.memory.filter;
    exports com.dwarfeng.subgrade.data.sdk.memory.io;
    exports com.dwarfeng.subgrade.data.sdk.mybatis;
    exports com.dwarfeng.subgrade.data.sdk.redis.formatter;
    exports com.dwarfeng.subgrade.data.sdk.redis.serialize;
    exports com.dwarfeng.subgrade.data.sdk.service;
    exports com.dwarfeng.subgrade.data.sdk.service.custom.operation;
    exports com.dwarfeng.subgrade.data.impl.bean;
    exports com.dwarfeng.subgrade.data.impl.cache;
    exports com.dwarfeng.subgrade.data.impl.dao.hibernate;
    exports com.dwarfeng.subgrade.data.impl.dao.jdbc;
    exports com.dwarfeng.subgrade.data.impl.dao.memory;
    exports com.dwarfeng.subgrade.data.impl.dao.mybatis;
    exports com.dwarfeng.subgrade.data.impl.dao.redis;
    exports com.dwarfeng.subgrade.data.impl.generation;
    exports com.dwarfeng.subgrade.data.impl.handler;
    exports com.dwarfeng.subgrade.data.impl.service;
}
